easy_admin:
    site_name: 'Cook Your Meeting - Administration'
    design:
        brand_color: '#d6a400'
        menu:
            - { label: 'Gestion des Messages'}
            - { entity: 'Contact', label: 'Messages' }
            - { label: 'Gestion Arbre' }
            - { entity: 'Duree', label: 'Durée' }
            - Participant
            - { entity: 'Categorie', label: 'Catégorie' }
            - { entity: 'Sous_Categorie', label: 'Sous_Catégorie' }
            - { entity: 'Parametrage_Arbre', label: 'Paramètrage_Arbre' }
            - { label: 'Gestion Design'}
            - Design
            - { label: 'Gestion Ressource'}
            - Ressource
            - { label: 'Gestion Comment ça Marche'}
            - Comment_Ca_Marche
            - { label: 'Gestion Boutique'}
            - Boutique
            - { label: 'Gestion Bas de Page'}
            - { entity: 'Footer', label: 'Paramètrage bas de page' }
            - { label: 'Gestion des CGU'}
            - { entity: 'Cgu', label: 'CGU' }
            - { label: 'Gestion Email Admin'}
            - Utilisateur
    entities:
        Duree:
            class: App\Entity\Duree
            help: 'Cette section permet de modifier les DUREES pour le paramétrage des Design'
            list:
                title: "Admin des Durées"
                fields:
                    - id
                    - { property: 'duree', label: 'Durée' }
            form:
                fields:
                    - { property: 'duree', label: 'Durée' }

        Participant:
            class: App\Entity\Groupe
            help: 'Cette section permet de modifier les PARTICIPANTS pour le paramétrage des Design'
            list:
                title: "Admin des Participants"
                fields:
                    - id
                    - { property: 'groupe', label: 'Nombre de participants' }
            form:
                fields:
                    - { property: 'groupe', label: 'Nombre de participants' }
        Categorie:
            help: 'Cette section permet de modifier les CATEGORIES. Attention certains objets sont fixes et ne peuvent pas être modifier (frise, 5 étapes).'
            class: App\Entity\Categorie
            disabled_actions: ['new', 'delete']
            list:
                title: "Admin des Catégories"
                fields:
                    - id
                    - { property: 'nom', label: 'Nom de la catégorie' }
        Sous_Categorie:
            help: 'Cette section permet de modifier les SOUS-CATEGORIES'
            class: App\Entity\Carte
            list:
                title: "Admin des Sous-Catégories"
                fields:
                    - id
                    - { property: 'nom', label: 'Nom sous-catégorie' }
            form:
                fields:
                    - { property: 'nom', label: 'Nom sous-catégorie' }
        Parametrage_Arbre:
            class: App\Entity\Correspondance
            help: 'Cette section permet de modifier l arbre en lui rattachant des exercices'
            list:
                title: "Admin des Correspondances"
                fields:
                    - { property: 'duree', label: 'Durée' }
                    - { property: 'groupe', label: 'Participants' }
                    - { property: 'categorie', label: 'Catégories' }
                    - { property: 'carte', label: 'Sous-catégories' }
                    - { property: 'ExerciceId', label: 'N° Exercice' }
            form:
                fields:
#                   - { property: 'categorie', type: 'easyadmin_autocomplete' }
                    - { property: 'duree', label: 'Durée' }
                    - { property: 'groupe', label: 'Participants' }
                    - { property: 'categorie', label: 'Catégories' }
                    - { property: 'carte', label: 'Sous-catégories' }
                    - { property: 'ExerciceId', type: 'text', label: 'N° Exercice' }
        Design:
            help: 'Cette section permet d administrer les Designs réalisé sur le site CYM'
            class: App\Entity\Ressource
            disabled_actions: ['new']
            list:
                title: "Admin des Designs"
                fields:
                    - { property: 'titre', label: 'Titre Design' }
                    - { property: 'duree', label: 'Durée' }
                    - { property: 'groupe', label: 'Participants' }
                    - { property: 'cc', label: 'Ex. Créer le champ' }
                    - { property: 'eng', label: 'Ex. Engagement' }
                    - { property: 'syn', label: ' Ex. Synergie' }
                    - { property: 'anc', label: 'Ex. Ancrage' }
                    - { property: 'dec', label: 'Ex. Déclusion' }
            edit:
                fields:
                    - { property: 'titre', label: 'Titre Design' }
        Comment_Ca_Marche:
            help: 'Cette section permet de modifier la partie COMMENT CA MARCHE du site CYM'
            class: App\Entity\CCM
            list:
                title: "Admin Comment ça Marche"
            form:
                fields:
                    - titre
                    - description
                    - { property: 'image', type: 'file_upload' }
                    - { property: 'image_filename', label: 'Nom du fichier image (avec extension)' }
        Ressource:
            help: 'Cette section permet de modifier la partie RESSOURCES du site CYM'
            class: App\Entity\Wiki
            list:
                title: "Admin Ressources"
            form:
                fields:
                    - titre
                    - description
                    - { property: 'image', type: 'file_upload' }
                    - { property: 'image_filename', label: 'Nom du fichier image (avec extension)' }
        Boutique:
            help: 'Cette section permet de modifier la partie BOUTIQUE du site CYM'
            class: App\Entity\Boutique
            list:
                title: "Admin Boutique"
                fields:
                    - titre
                    - description
                    - { property: 'image', type: 'file_upload' }
                    - { property: 'image_filename', label: 'Nom du fichier image (avec extension)' }
                    - lien
            new:
                fields:
                    - titre
                    - description
                    - { property: 'image', type: 'file_upload' }
                    - { property: 'image_filename', label: 'Nom du fichier image (avec extension)' }
                    - lien
            edit:
                fields:
                    - titre
                    - description
                    - lien
        Footer:
            help: 'Cette section permet de modifier les bas de page dans la portion marron'
            class: App\Entity\Footer
            disabled_actions: ['new', 'delete']
            list:
                title: "Admin Bas de Page"
                fields:
                    - Page
                    - titre
                    - { property: 'soustitre', label: 'Sous-Titre' }
                    - description
            form:
                fields:
                    - titre
                    - { property: 'soustitre', label: 'Sous-Titre' }
                    - description
        Utilisateur:
            class: App\Entity\User
            disabled_actions: ['new', 'delete']
            list:
                help: 'Dans cette section vous pouvez modifier votre adresse email. Pour changer votre mot de passe contactez Adrien MECHIN : adrien.mechin@gmail.com'
                title: "Admin des droits d'utilisateur"
            form:
                fields:
                    - email
        Contact:
            class: App\Entity\Contact
            disabled_actions: ['new']
            list:
                help: 'Dans cette section vous pouvez consulter les messages qui vous ont été envoyés.'
                title: "Admin des MESSAGES"
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'email', label: 'Email' }
                    - { property: 'subject', label: 'Sujet' }
                    - { property: 'text', label: 'Message' }
            form:
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'email', label: 'Email' }
                    - { property: 'subject', label: 'Sujet' }
                    - { property: 'text', label: 'Message' }
        Cgu:
            help: 'Cette section permet de modifier les Conditions Générales d Utilisation du site'
            class: App\Entity\Cgu
            list:
                title: "Admin CGU"
                fields:
                    - titre
                    - description
            new:
                fields:
                    - titre
                    - { property: 'description', type: 'textarea' }
            edit:
                fields:
                    - titre
                    - { property: 'description', type: 'textarea' }




